import type { OnboardingQuestion } from "./types"

export const onboardingQuestions: OnboardingQuestion[] = [
  {
    id: "source",
    type: "multiple-choice",
    question: "How did you hear about us?",
    emoji: "📢",
    required: false,
    options: [
      { id: "social_media", text: "Social media", emoji: "📱" },
      { id: "search_engine", text: "Search engine", emoji: "🔍" },
      { id: "friend_family", text: "Friend/family", emoji: "👥" },
      { id: "blog_article", text: "Blog/article", emoji: "📝" },
      { id: "podcast", text: "Podcast", emoji: "🎧" },
      { id: "app_store", text: "App store", emoji: "🛍️" },
      { id: "other", text: "Other", emoji: "❓" },
    ],
    analyticsEventName: "onboarding_source",
  },
  {
    id: "name",
    type: "text-input",
    question: "What should we call you?",
    emoji: "👋",
    required: true,
    validationRules: [
      { type: "required", message: "Please enter your name" },
      { type: "min-length", message: "Name must be at least 2 characters", value: 2 },
    ],
    analyticsEventName: "onboarding_name",
  },
  {
    id: "gender",
    type: "multiple-choice",
    question: "How do you identify?",
    emoji: "👤",
    required: true,
    options: [
      { id: "male", text: "Male", emoji: "👨" },
      { id: "female", text: "Female", emoji: "👩" },
      { id: "non_binary", text: "Non-binary", emoji: "🧑" },
      { id: "prefer_not_to_say", text: "Prefer not to say", emoji: "🤐" },
    ],
    analyticsEventName: "onboarding_gender",
  },
  {
    id: "wake_time",
    type: "time-picker",
    question: "Wake up time?",
    emoji: "⏰",
    required: true,
    analyticsEventName: "onboarding_wake_time",
  },
  {
    id: "situation",
    type: "multiple-choice",
    question: "Current situation?",
    emoji: "🎓",
    required: true,
    options: [
      { id: "student", text: "Student", emoji: "📚" },
      { id: "employee", text: "Employee", emoji: "💼" },
      { id: "employer", text: "Employer/Business Owner", emoji: "👔" },
      { id: "other", text: "Other", emoji: "🌟" },
    ],
    analyticsEventName: "onboarding_situation",
  },
  {
    id: "work_start_time",
    type: "time-picker",
    question: "Work/study start time?",
    emoji: "🕘",
    required: true,
    validationRules: [
      {
        type: "time-after",
        message: "Your work/study time cannot be earlier than your wake up time. Please select a later time.",
        dependsOn: "wake_time",
      },
    ],
    analyticsEventName: "onboarding_work_start_time",
  },
  {
    id: "work_mode",
    type: "multiple-choice",
    question: "How do you work/study?",
    emoji: "🏢",
    required: true,
    options: [
      { id: "in_person", text: "In-person", emoji: "🏫" },
      { id: "remote", text: "Remote", emoji: "🏠" },
      { id: "hybrid", text: "Hybrid", emoji: "🔄" },
      { id: "varies", text: "Varies", emoji: "📊" },
    ],
    analyticsEventName: "onboarding_work_mode",
  },
  {
    id: "bed_time",
    type: "multiple-choice",
    question: "Time in bed after waking?",
    emoji: "🛏",
    required: true,
    options: [
      { id: "immediate", text: "Immediate (0-5min)", emoji: "⚡" },
      { id: "few_minutes", text: "Few minutes (5-15min)", emoji: "⏱️" },
      { id: "quite_a_while", text: "Quite a while (15-30min)", emoji: "⏳" },
      { id: "way_too_long", text: "Way too long (30+min)", emoji: "😴" },
    ],
    analyticsEventName: "onboarding_bed_time",
  },
  {
    id: "energy_slumps",
    type: "multiple-choice",
    question: "Afternoon energy slumps?",
    emoji: "😴",
    required: true,
    options: [
      { id: "daily", text: "Yes almost daily", emoji: "📉" },
      { id: "sometimes", text: "Sometimes", emoji: "🔄" },
      { id: "rarely", text: "Rarely", emoji: "📈" },
      { id: "no", text: "No", emoji: "⚡" },
    ],
    analyticsEventName: "onboarding_energy_slumps",
  },
  {
    id: "morning_productivity",
    type: "multiple-choice",
    question: "Morning productivity feeling?",
    emoji: "📊",
    required: true,
    options: [
      { id: "very_productive", text: "Very productive (8-10)", emoji: "🚀" },
      { id: "moderate", text: "Moderate (5-7)", emoji: "📈" },
      { id: "somewhat", text: "Somewhat (3-4)", emoji: "📊" },
      { id: "not_productive", text: "Not productive (1-2)", emoji: "📉" },
    ],
    analyticsEventName: "onboarding_morning_productivity",
  },
  {
    id: "primary_goal",
    type: "multiple-choice",
    question: "Primary goal?",
    emoji: "🎯",
    required: true,
    options: [
      { id: "boost_energy", text: "Boost energy", emoji: "⚡" },
      { id: "increase_productivity", text: "Increase productivity", emoji: "📈" },
      { id: "build_habits", text: "Build habits", emoji: "🔄" },
      { id: "reduce_social_media", text: "Reduce social media", emoji: "📱" },
    ],
    analyticsEventName: "onboarding_primary_goal",
  },
  {
    id: "coffee_habits",
    type: "multiple-choice",
    question: "Coffee habits?",
    emoji: "☕",
    required: true,
    options: [
      { id: "every_morning", text: "Yes every morning", emoji: "☕" },
      { id: "sometimes", text: "Yes sometimes", emoji: "🔄" },
      { id: "tea", text: "No but tea", emoji: "🍵" },
      { id: "water", text: "No just water", emoji: "💧" },
    ],
    analyticsEventName: "onboarding_coffee_habits",
  },
  {
    id: "social_media",
    type: "multiple-choice",
    question: "Social media checking?",
    emoji: "📱",
    required: true,
    options: [
      { id: "immediately", text: "Immediately", emoji: "⚡" },
      { id: "within_30", text: "Within 30 minutes", emoji: "⏱️" },
      { id: "after_hour", text: "After an hour", emoji: "⏳" },
      { id: "avoid", text: "Avoid in morning", emoji: "🚫" },
    ],
    analyticsEventName: "onboarding_social_media",
  },
  {
    id: "weekend_productivity",
    type: "multiple-choice",
    question: "Weekend productivity?",
    emoji: "📅",
    required: true,
    options: [
      { id: "every_day", text: "Yes every day", emoji: "📆" },
      { id: "relaxed", text: "Yes but relaxed", emoji: "🧘" },
      { id: "weekdays_only", text: "Weekdays only", emoji: "💼" },
      { id: "flexible", text: "Flexible weekends", emoji: "🔄" },
    ],
    analyticsEventName: "onboarding_weekend_productivity",
  },
]
